import "./CustomizerUi.css";

function CustomizerUi() {
    return (
        <main className="design__customizer">
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum suscipit, magni voluptas adipisci quas ipsam voluptates et neque! Necessitatibus omnis quibusdam rerum corrupti accusantium quas asperiores tenetur ut? Similique maxime provident odio ab iure at, soluta aliquam. Beatae ipsa minima similique doloribus corporis, quasi illum numquam possimus, incidunt accusamus voluptatem.</p>
            <p>Dignissimos cupiditate impedit recusandae sit ipsum reprehenderit alias quidem quas atque quam iure quis sunt, nemo voluptates harum laborum veniam, laboriosam non hic nobis? Molestias iure cum neque reprehenderit pariatur, saepe laborum harum laudantium veritatis culpa perspiciatis ut repellat obcaecati, praesentium eligendi incidunt in nisi maiores enim ipsam ex. Eveniet.</p>
            <p>Blanditiis ipsum pariatur, officia asperiores amet cum sint, praesentium, minima eaque fugit eveniet est culpa numquam autem obcaecati magni placeat aliquam. Ipsam ab ipsum voluptas, minus, ratione neque natus deleniti obcaecati quas debitis odit et possimus voluptates adipisci velit repudiandae eum magnam sapiente? Quos sint maiores vero consectetur iure laboriosam?</p>
            <p>Optio explicabo cum veniam fugiat delectus fuga dolorem nesciunt labore totam. Ullam numquam atque aliquam voluptates, iusto vel nulla illum sint assumenda nesciunt tenetur reiciendis quo deleniti nobis iure possimus quasi accusantium, tempora excepturi officiis. Voluptates nisi dicta eaque, et nam ipsa accusamus quidem minima soluta sequi blanditiis velit sit!</p>
            <p>Quia animi dolor saepe nostrum itaque dolorem commodi consequatur, atque a laudantium temporibus! Pariatur delectus vitae aliquid debitis ratione nesciunt totam ipsum aperiam accusamus cupiditate repudiandae facere dolorem magni, ab obcaecati sit odit sapiente commodi porro labore saepe. Iste in ipsa eum laborum assumenda cumque eligendi unde quo inventore laboriosam.</p>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum suscipit, magni voluptas adipisci quas ipsam voluptates et neque! Necessitatibus omnis quibusdam rerum corrupti accusantium quas asperiores tenetur ut? Similique maxime provident odio ab iure at, soluta aliquam. Beatae ipsa minima similique doloribus corporis, quasi illum numquam possimus, incidunt accusamus voluptatem.</p>
            <p>Dignissimos cupiditate impedit recusandae sit ipsum reprehenderit alias quidem quas atque quam iure quis sunt, nemo voluptates harum laborum veniam, laboriosam non hic nobis? Molestias iure cum neque reprehenderit pariatur, saepe laborum harum laudantium veritatis culpa perspiciatis ut repellat obcaecati, praesentium eligendi incidunt in nisi maiores enim ipsam ex. Eveniet.</p>
            <p>Blanditiis ipsum pariatur, officia asperiores amet cum sint, praesentium, minima eaque fugit eveniet est culpa numquam autem obcaecati magni placeat aliquam. Ipsam ab ipsum voluptas, minus, ratione neque natus deleniti obcaecati quas debitis odit et possimus voluptates adipisci velit repudiandae eum magnam sapiente? Quos sint maiores vero consectetur iure laboriosam?</p>
            <p>Optio explicabo cum veniam fugiat delectus fuga dolorem nesciunt labore totam. Ullam numquam atque aliquam voluptates, iusto vel nulla illum sint assumenda nesciunt tenetur reiciendis quo deleniti nobis iure possimus quasi accusantium, tempora excepturi officiis. Voluptates nisi dicta eaque, et nam ipsa accusamus quidem minima soluta sequi blanditiis velit sit!</p>
            <p>Quia animi dolor saepe nostrum itaque dolorem commodi consequatur, atque a laudantium temporibus! Pariatur delectus vitae aliquid debitis ratione nesciunt totam ipsum aperiam accusamus cupiditate repudiandae facere dolorem magni, ab obcaecati sit odit sapiente commodi porro labore saepe. Iste in ipsa eum laborum assumenda cumque eligendi unde quo inventore laboriosam.</p>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum suscipit, magni voluptas adipisci quas ipsam voluptates et neque! Necessitatibus omnis quibusdam rerum corrupti accusantium quas asperiores tenetur ut? Similique maxime provident odio ab iure at, soluta aliquam. Beatae ipsa minima similique doloribus corporis, quasi illum numquam possimus, incidunt accusamus voluptatem.</p>
            <p>Dignissimos cupiditate impedit recusandae sit ipsum reprehenderit alias quidem quas atque quam iure quis sunt, nemo voluptates harum laborum veniam, laboriosam non hic nobis? Molestias iure cum neque reprehenderit pariatur, saepe laborum harum laudantium veritatis culpa perspiciatis ut repellat obcaecati, praesentium eligendi incidunt in nisi maiores enim ipsam ex. Eveniet.</p>
            <p>Blanditiis ipsum pariatur, officia asperiores amet cum sint, praesentium, minima eaque fugit eveniet est culpa numquam autem obcaecati magni placeat aliquam. Ipsam ab ipsum voluptas, minus, ratione neque natus deleniti obcaecati quas debitis odit et possimus voluptates adipisci velit repudiandae eum magnam sapiente? Quos sint maiores vero consectetur iure laboriosam?</p>
            <p>Optio explicabo cum veniam fugiat delectus fuga dolorem nesciunt labore totam. Ullam numquam atque aliquam voluptates, iusto vel nulla illum sint assumenda nesciunt tenetur reiciendis quo deleniti nobis iure possimus quasi accusantium, tempora excepturi officiis. Voluptates nisi dicta eaque, et nam ipsa accusamus quidem minima soluta sequi blanditiis velit sit!</p>
            <p>Quia animi dolor saepe nostrum itaque dolorem commodi consequatur, atque a laudantium temporibus! Pariatur delectus vitae aliquid debitis ratione nesciunt totam ipsum aperiam accusamus cupiditate repudiandae facere dolorem magni, ab obcaecati sit odit sapiente commodi porro labore saepe. Iste in ipsa eum laborum assumenda cumque eligendi unde quo inventore laboriosam.</p>
        </main>
    );
}

export default CustomizerUi;
